---
name: Documentation

"on":
  schedule:
    - cron: "0 0 * * 0" # every week at midnight
  push:
    paths:
      - "**.md"
      - "docs/**"
  pull_request:
    paths:
      - "**.md"
      - "docs/**"

jobs:
  docs:
    name: Build documentation & check links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install Poetry
        run: |
          python .github/workflows/pipx_install_helper.py -p poetry
          poetry --version
      - name: Install Nox
        run: |
          python .github/workflows/pipx_install_helper.py -p nox
          python .github/workflows/pipx_install_helper.py -m inject -p nox-poetry --package-environment nox
          nox --version
      - name: Build documentation
        run: nox --force-color --session=docs-build

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build
